In [6]:
import pandas as pd
from pathlib import Path

In [7]:
base_dir = Path().resolve().parents[1]
print(f"Base directory: {base_dir}")
interim_dir = base_dir /"Patricia-Promise-Immo"/"data" / "interim"
print(f"Interim directory: {interim_dir}")
parquet_path = interim_dir / "all_immo_entries.parquet"

df = pd.read_parquet(parquet_path)

Base directory: D:\ProjectFolderDevAI_2025-2026\Immo_project
Interim directory: D:\ProjectFolderDevAI_2025-2026\Immo_project\Patricia-Promise-Immo\data\interim

In [8]:
df['Type local'] = df['Type local'].replace({
    'Dépendance': 1,
    'Maison': 2,
    'Appartement': 3
})

C:\Users\PATRICIA\AppData\Local\Temp\ipykernel_9968\2355931518.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Type local'] = df['Type local'].replace({

In [9]:
ints = []
objects = []
floats = []
for column in df.columns.to_list():
    data_type = df[column].dtypes
    print(data_type)
    if data_type == 'int64':
        ints.append(column)
    if data_type == 'object':
        objects.append(column)
    if data_type == 'float64':
        floats.append(column)

int64
float64
float64
float64
float64
float64
float64
float64
int64
object
object
float64
float64
object
object
object
object
int64
object
int64
int64
float64
object
int64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int64
float64
float64
float64
float64
float64
object
object
float64

In [10]:

df_no_nan = df.fillna(value=0)

In [11]:
df_no_nan.columns

Index(['Unnamed: 0', 'Identifiant de document', 'Reference document',
       '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI',
       '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation',
       'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie',
       'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune',
       'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot',
       'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot',
       '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot',
       'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot',
       'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local',
       'Surface reelle bati', 'Nombre pieces principales', 'Nature culture',
       'Nature culture speciale', 'Surface terrain'],
      dtype='object')

In [12]:
df_no_nan[objects]

,Date mutation,Nature mutation,B/T/Q,Type de voie,Code voie,Voie,Commune,Section,Nature culture,Nature culture speciale
0,07/01/2025,Vente,0,0,B078,FARGES,FARGES,B,J,0
1,07/01/2025,Vente,0,RUE,0090,DE LA REPUBLIQUE,FARGES,B,S,0
2,07/01/2025,Vente,0,RUE,0090,DE LA REPUBLIQUE,FARGES,B,S,0
3,06/01/2025,Vente,0,0,B158,LE VILLAGE,MONTANGES,AC,S,0
4,06/01/2025,Vente,0,0,B158,LE VILLAGE,MONTANGES,AC,J,0
...,...,...,...,...,...,...,...,...,...,...
201295,07/01/2025,Vente,0,0,B010,LA CURTERIE,MAGNIEU,B,AB,0
201296,07/01/2025,Vente,0,0,B010,LA CURTERIE,MAGNIEU,B,AB,0
201297,06/01/2025,Vente,0,0,B036,VILLAGE DE CHARNOZ,CHARNOZ-SUR-AIN,B,J,0
201298,14/01/2025,Vente,0,RUE,0443,DU PRE PAQUIER,SAINT-LAURENT-SUR-SAONE,A,0,0
201299,14/01/2025,Vente,0,RUE,0443,DU PRE PAQUIER,SAINT-LAURENT-SUR-SAONE,A,0,0

In [13]:
df_final = df_no_nan.drop(columns=objects)

In [14]:
df_final = df_final.drop(columns=['Unnamed: 0','No voie'])

In [ ]:
df_final.to_parquet(parquet_path)

OSError: Cannot save file into a non-existent directory: 'outputs'

In [ ]:
df_final

,No disposition,Valeur fonciere,Code postal,Code departement,Code commune,Prefixe de section,No plan,1er lot,Surface Carrez du 1er lot,2eme lot,Surface Carrez du 2eme lot,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain
0,1,468000.0,1550,1,158,0.0,815,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,78.0
1,1,468000.0,1550,1,158,0.0,910,0.0,0.00,0.0,0.0,0,1.0,2.0,111.0,5.0,133.0
2,1,468000.0,1550,1,158,0.0,910,0.0,0.00,0.0,0.0,0,3.0,1.0,0.0,0.0,133.0
3,1,180000.0,1200,1,257,0.0,334,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,46.0
4,1,180000.0,1200,1,257,0.0,338,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201295,1,295000.0,1300,1,227,0.0,1847,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,402.0
201296,1,295000.0,1300,1,227,0.0,1848,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,4.0
201297,1,81500.0,1800,1,88,0.0,396,0.0,0.00,0.0,0.0,0,0.0,0.0,0.0,0.0,261.0
201298,1,78000.0,1750,1,370,0.0,680,49.0,48.62,0.0,0.0,1,2.0,3.0,48.0,2.0,0.0
201299,1,78000.0,1750,1,370,0.0,680,125.0,0.00,0.0,0.0,1,3.0,1.0,0.0,0.0,0.0